//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.15 at 01:11:28 PM CST 
//


package com.bny.castxc.schedule.summary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="CPSCN234" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSCN235" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSCP091" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CASCP087" type="{}STRING_50" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="ID_RSSD" use="required" type="{}INTEGER" />
 *       &lt;attribute name="D_DT" use="required" type="{}DATE_TIME" />
 *       &lt;attribute name="CCARP006" use="required" type="{}STRING_50" />
 *       &lt;attribute name="CCARP083" use="required" type="{}STRING_50" />
 *       &lt;attribute name="TRANSTYPE" use="required" type="{}TRANSTYPE_IUD" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "SMRY_Data_Collect_OTTI_CUSIP")
public class SMRYDataCollectOTTICUSIP {

    @XmlElement(name = "CPSCN234")
    protected String cpscn234;
    @XmlElement(name = "CPSCN235")
    protected String cpscn235;
    @XmlElement(name = "CPSCP091")
    protected String cpscp091;
    @XmlElement(name = "CASCP087")
    protected String cascp087;
    @XmlAttribute(name = "ID_RSSD", required = true)
    protected int idrssd;
    @XmlAttribute(name = "D_DT", required = true)
    protected XMLGregorianCalendar ddt;
    @XmlAttribute(name = "CCARP006", required = true)
    protected String ccarp006;
    @XmlAttribute(name = "CCARP083", required = true)
    protected String ccarp083;
    @XmlAttribute(name = "TRANSTYPE", required = true)
    protected TRANSTYPEIUD transtype;

    /**
     * Gets the value of the cpscn234 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSCN234() {
        return cpscn234;
    }

    /**
     * Sets the value of the cpscn234 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSCN234(String value) {
        this.cpscn234 = value;
    }

    /**
     * Gets the value of the cpscn235 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSCN235() {
        return cpscn235;
    }

    /**
     * Sets the value of the cpscn235 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSCN235(String value) {
        this.cpscn235 = value;
    }

    /**
     * Gets the value of the cpscp091 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSCP091() {
        return cpscp091;
    }

    /**
     * Sets the value of the cpscp091 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSCP091(String value) {
        this.cpscp091 = value;
    }

    /**
     * Gets the value of the cascp087 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCASCP087() {
        return cascp087;
    }

    /**
     * Sets the value of the cascp087 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCASCP087(String value) {
        this.cascp087 = value;
    }

    /**
     * Gets the value of the idrssd property.
     * 
     */
    public int getIDRSSD() {
        return idrssd;
    }

    /**
     * Sets the value of the idrssd property.
     * 
     */
    public void setIDRSSD(int value) {
        this.idrssd = value;
    }

    /**
     * Gets the value of the ddt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDDT() {
        return ddt;
    }

    /**
     * Sets the value of the ddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDDT(XMLGregorianCalendar value) {
        this.ddt = value;
    }

    /**
     * Gets the value of the ccarp006 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCARP006() {
        return ccarp006;
    }

    /**
     * Sets the value of the ccarp006 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCARP006(String value) {
        this.ccarp006 = value;
    }

    /**
     * Gets the value of the ccarp083 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCARP083() {
        return ccarp083;
    }

    /**
     * Sets the value of the ccarp083 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCARP083(String value) {
        this.ccarp083 = value;
    }

    /**
     * Gets the value of the transtype property.
     * 
     * @return
     *     possible object is
     *     {@link TRANSTYPEIUD }
     *     
     */
    public TRANSTYPEIUD getTRANSTYPE() {
        return transtype;
    }

    /**
     * Sets the value of the transtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRANSTYPEIUD }
     *     
     */
    public void setTRANSTYPE(TRANSTYPEIUD value) {
        this.transtype = value;
    }

}
