//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.15 at 01:11:28 PM CST 
//


package com.bny.castxc.schedule.summary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="CPSVP098" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP099" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP100" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP101" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP102" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP103" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP104" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP105" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP106" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP107" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP108" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP109" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP110" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP111" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP112" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP114" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP115" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP116" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP117" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP118" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP119" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP120" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP121" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP122" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP123" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP124" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP125" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP126" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP127" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP128" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP130" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP131" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP132" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP133" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP134" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP135" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP136" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP137" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP138" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP139" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP140" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP141" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP142" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP143" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP144" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP145" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP147" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP148" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP149" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP150" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP151" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP152" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP153" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP154" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP155" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP156" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP157" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP158" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP159" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP160" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP161" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP163" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP164" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP165" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP166" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP167" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP168" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP169" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP170" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP171" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP172" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP173" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP174" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP175" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP176" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP177" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP179" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP180" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP181" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP182" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP183" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP184" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP185" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP186" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP187" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP188" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP189" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP190" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP191" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP192" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVP193" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS646" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS647" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS648" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS649" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS650" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS651" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS652" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS653" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS654" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS655" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS656" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS657" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS658" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS659" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS660" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS661" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS662" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS663" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS664" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS665" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS666" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS667" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS668" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS669" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS670" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS671" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS672" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS673" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS674" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSVS675" type="{}STRING_50" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="ID_RSSD" use="required" type="{}INTEGER" />
 *       &lt;attribute name="D_DT" use="required" type="{}DATE_TIME" />
 *       &lt;attribute name="CCARP006" use="required" type="{}STRING_50" />
 *       &lt;attribute name="CPSVN998" use="required" type="{}STRING_50" />
 *       &lt;attribute name="TRANSTYPE" use="required" type="{}TRANSTYPE_IUD" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "SMRY_Data_Collect_VINT")
public class SMRYDataCollectVINT {

    @XmlElement(name = "CPSVP098")
    protected String cpsvp098;
    @XmlElement(name = "CPSVP099")
    protected String cpsvp099;
    @XmlElement(name = "CPSVP100")
    protected String cpsvp100;
    @XmlElement(name = "CPSVP101")
    protected String cpsvp101;
    @XmlElement(name = "CPSVP102")
    protected String cpsvp102;
    @XmlElement(name = "CPSVP103")
    protected String cpsvp103;
    @XmlElement(name = "CPSVP104")
    protected String cpsvp104;
    @XmlElement(name = "CPSVP105")
    protected String cpsvp105;
    @XmlElement(name = "CPSVP106")
    protected String cpsvp106;
    @XmlElement(name = "CPSVP107")
    protected String cpsvp107;
    @XmlElement(name = "CPSVP108")
    protected String cpsvp108;
    @XmlElement(name = "CPSVP109")
    protected String cpsvp109;
    @XmlElement(name = "CPSVP110")
    protected String cpsvp110;
    @XmlElement(name = "CPSVP111")
    protected String cpsvp111;
    @XmlElement(name = "CPSVP112")
    protected String cpsvp112;
    @XmlElement(name = "CPSVP114")
    protected String cpsvp114;
    @XmlElement(name = "CPSVP115")
    protected String cpsvp115;
    @XmlElement(name = "CPSVP116")
    protected String cpsvp116;
    @XmlElement(name = "CPSVP117")
    protected String cpsvp117;
    @XmlElement(name = "CPSVP118")
    protected String cpsvp118;
    @XmlElement(name = "CPSVP119")
    protected String cpsvp119;
    @XmlElement(name = "CPSVP120")
    protected String cpsvp120;
    @XmlElement(name = "CPSVP121")
    protected String cpsvp121;
    @XmlElement(name = "CPSVP122")
    protected String cpsvp122;
    @XmlElement(name = "CPSVP123")
    protected String cpsvp123;
    @XmlElement(name = "CPSVP124")
    protected String cpsvp124;
    @XmlElement(name = "CPSVP125")
    protected String cpsvp125;
    @XmlElement(name = "CPSVP126")
    protected String cpsvp126;
    @XmlElement(name = "CPSVP127")
    protected String cpsvp127;
    @XmlElement(name = "CPSVP128")
    protected String cpsvp128;
    @XmlElement(name = "CPSVP130")
    protected String cpsvp130;
    @XmlElement(name = "CPSVP131")
    protected String cpsvp131;
    @XmlElement(name = "CPSVP132")
    protected String cpsvp132;
    @XmlElement(name = "CPSVP133")
    protected String cpsvp133;
    @XmlElement(name = "CPSVP134")
    protected String cpsvp134;
    @XmlElement(name = "CPSVP135")
    protected String cpsvp135;
    @XmlElement(name = "CPSVP136")
    protected String cpsvp136;
    @XmlElement(name = "CPSVP137")
    protected String cpsvp137;
    @XmlElement(name = "CPSVP138")
    protected String cpsvp138;
    @XmlElement(name = "CPSVP139")
    protected String cpsvp139;
    @XmlElement(name = "CPSVP140")
    protected String cpsvp140;
    @XmlElement(name = "CPSVP141")
    protected String cpsvp141;
    @XmlElement(name = "CPSVP142")
    protected String cpsvp142;
    @XmlElement(name = "CPSVP143")
    protected String cpsvp143;
    @XmlElement(name = "CPSVP144")
    protected String cpsvp144;
    @XmlElement(name = "CPSVP145")
    protected String cpsvp145;
    @XmlElement(name = "CPSVP147")
    protected String cpsvp147;
    @XmlElement(name = "CPSVP148")
    protected String cpsvp148;
    @XmlElement(name = "CPSVP149")
    protected String cpsvp149;
    @XmlElement(name = "CPSVP150")
    protected String cpsvp150;
    @XmlElement(name = "CPSVP151")
    protected String cpsvp151;
    @XmlElement(name = "CPSVP152")
    protected String cpsvp152;
    @XmlElement(name = "CPSVP153")
    protected String cpsvp153;
    @XmlElement(name = "CPSVP154")
    protected String cpsvp154;
    @XmlElement(name = "CPSVP155")
    protected String cpsvp155;
    @XmlElement(name = "CPSVP156")
    protected String cpsvp156;
    @XmlElement(name = "CPSVP157")
    protected String cpsvp157;
    @XmlElement(name = "CPSVP158")
    protected String cpsvp158;
    @XmlElement(name = "CPSVP159")
    protected String cpsvp159;
    @XmlElement(name = "CPSVP160")
    protected String cpsvp160;
    @XmlElement(name = "CPSVP161")
    protected String cpsvp161;
    @XmlElement(name = "CPSVP163")
    protected String cpsvp163;
    @XmlElement(name = "CPSVP164")
    protected String cpsvp164;
    @XmlElement(name = "CPSVP165")
    protected String cpsvp165;
    @XmlElement(name = "CPSVP166")
    protected String cpsvp166;
    @XmlElement(name = "CPSVP167")
    protected String cpsvp167;
    @XmlElement(name = "CPSVP168")
    protected String cpsvp168;
    @XmlElement(name = "CPSVP169")
    protected String cpsvp169;
    @XmlElement(name = "CPSVP170")
    protected String cpsvp170;
    @XmlElement(name = "CPSVP171")
    protected String cpsvp171;
    @XmlElement(name = "CPSVP172")
    protected String cpsvp172;
    @XmlElement(name = "CPSVP173")
    protected String cpsvp173;
    @XmlElement(name = "CPSVP174")
    protected String cpsvp174;
    @XmlElement(name = "CPSVP175")
    protected String cpsvp175;
    @XmlElement(name = "CPSVP176")
    protected String cpsvp176;
    @XmlElement(name = "CPSVP177")
    protected String cpsvp177;
    @XmlElement(name = "CPSVP179")
    protected String cpsvp179;
    @XmlElement(name = "CPSVP180")
    protected String cpsvp180;
    @XmlElement(name = "CPSVP181")
    protected String cpsvp181;
    @XmlElement(name = "CPSVP182")
    protected String cpsvp182;
    @XmlElement(name = "CPSVP183")
    protected String cpsvp183;
    @XmlElement(name = "CPSVP184")
    protected String cpsvp184;
    @XmlElement(name = "CPSVP185")
    protected String cpsvp185;
    @XmlElement(name = "CPSVP186")
    protected String cpsvp186;
    @XmlElement(name = "CPSVP187")
    protected String cpsvp187;
    @XmlElement(name = "CPSVP188")
    protected String cpsvp188;
    @XmlElement(name = "CPSVP189")
    protected String cpsvp189;
    @XmlElement(name = "CPSVP190")
    protected String cpsvp190;
    @XmlElement(name = "CPSVP191")
    protected String cpsvp191;
    @XmlElement(name = "CPSVP192")
    protected String cpsvp192;
    @XmlElement(name = "CPSVP193")
    protected String cpsvp193;
    @XmlElement(name = "CPSVS646")
    protected String cpsvs646;
    @XmlElement(name = "CPSVS647")
    protected String cpsvs647;
    @XmlElement(name = "CPSVS648")
    protected String cpsvs648;
    @XmlElement(name = "CPSVS649")
    protected String cpsvs649;
    @XmlElement(name = "CPSVS650")
    protected String cpsvs650;
    @XmlElement(name = "CPSVS651")
    protected String cpsvs651;
    @XmlElement(name = "CPSVS652")
    protected String cpsvs652;
    @XmlElement(name = "CPSVS653")
    protected String cpsvs653;
    @XmlElement(name = "CPSVS654")
    protected String cpsvs654;
    @XmlElement(name = "CPSVS655")
    protected String cpsvs655;
    @XmlElement(name = "CPSVS656")
    protected String cpsvs656;
    @XmlElement(name = "CPSVS657")
    protected String cpsvs657;
    @XmlElement(name = "CPSVS658")
    protected String cpsvs658;
    @XmlElement(name = "CPSVS659")
    protected String cpsvs659;
    @XmlElement(name = "CPSVS660")
    protected String cpsvs660;
    @XmlElement(name = "CPSVS661")
    protected String cpsvs661;
    @XmlElement(name = "CPSVS662")
    protected String cpsvs662;
    @XmlElement(name = "CPSVS663")
    protected String cpsvs663;
    @XmlElement(name = "CPSVS664")
    protected String cpsvs664;
    @XmlElement(name = "CPSVS665")
    protected String cpsvs665;
    @XmlElement(name = "CPSVS666")
    protected String cpsvs666;
    @XmlElement(name = "CPSVS667")
    protected String cpsvs667;
    @XmlElement(name = "CPSVS668")
    protected String cpsvs668;
    @XmlElement(name = "CPSVS669")
    protected String cpsvs669;
    @XmlElement(name = "CPSVS670")
    protected String cpsvs670;
    @XmlElement(name = "CPSVS671")
    protected String cpsvs671;
    @XmlElement(name = "CPSVS672")
    protected String cpsvs672;
    @XmlElement(name = "CPSVS673")
    protected String cpsvs673;
    @XmlElement(name = "CPSVS674")
    protected String cpsvs674;
    @XmlElement(name = "CPSVS675")
    protected String cpsvs675;
    @XmlAttribute(name = "ID_RSSD", required = true)
    protected int idrssd;
    @XmlAttribute(name = "D_DT", required = true)
    protected XMLGregorianCalendar ddt;
    @XmlAttribute(name = "CCARP006", required = true)
    protected String ccarp006;
    @XmlAttribute(name = "CPSVN998", required = true)
    protected String cpsvn998;
    @XmlAttribute(name = "TRANSTYPE", required = true)
    protected TRANSTYPEIUD transtype;

    /**
     * Gets the value of the cpsvp098 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP098() {
        return cpsvp098;
    }

    /**
     * Sets the value of the cpsvp098 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP098(String value) {
        this.cpsvp098 = value;
    }

    /**
     * Gets the value of the cpsvp099 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP099() {
        return cpsvp099;
    }

    /**
     * Sets the value of the cpsvp099 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP099(String value) {
        this.cpsvp099 = value;
    }

    /**
     * Gets the value of the cpsvp100 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP100() {
        return cpsvp100;
    }

    /**
     * Sets the value of the cpsvp100 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP100(String value) {
        this.cpsvp100 = value;
    }

    /**
     * Gets the value of the cpsvp101 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP101() {
        return cpsvp101;
    }

    /**
     * Sets the value of the cpsvp101 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP101(String value) {
        this.cpsvp101 = value;
    }

    /**
     * Gets the value of the cpsvp102 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP102() {
        return cpsvp102;
    }

    /**
     * Sets the value of the cpsvp102 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP102(String value) {
        this.cpsvp102 = value;
    }

    /**
     * Gets the value of the cpsvp103 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP103() {
        return cpsvp103;
    }

    /**
     * Sets the value of the cpsvp103 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP103(String value) {
        this.cpsvp103 = value;
    }

    /**
     * Gets the value of the cpsvp104 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP104() {
        return cpsvp104;
    }

    /**
     * Sets the value of the cpsvp104 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP104(String value) {
        this.cpsvp104 = value;
    }

    /**
     * Gets the value of the cpsvp105 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP105() {
        return cpsvp105;
    }

    /**
     * Sets the value of the cpsvp105 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP105(String value) {
        this.cpsvp105 = value;
    }

    /**
     * Gets the value of the cpsvp106 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP106() {
        return cpsvp106;
    }

    /**
     * Sets the value of the cpsvp106 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP106(String value) {
        this.cpsvp106 = value;
    }

    /**
     * Gets the value of the cpsvp107 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP107() {
        return cpsvp107;
    }

    /**
     * Sets the value of the cpsvp107 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP107(String value) {
        this.cpsvp107 = value;
    }

    /**
     * Gets the value of the cpsvp108 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP108() {
        return cpsvp108;
    }

    /**
     * Sets the value of the cpsvp108 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP108(String value) {
        this.cpsvp108 = value;
    }

    /**
     * Gets the value of the cpsvp109 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP109() {
        return cpsvp109;
    }

    /**
     * Sets the value of the cpsvp109 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP109(String value) {
        this.cpsvp109 = value;
    }

    /**
     * Gets the value of the cpsvp110 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP110() {
        return cpsvp110;
    }

    /**
     * Sets the value of the cpsvp110 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP110(String value) {
        this.cpsvp110 = value;
    }

    /**
     * Gets the value of the cpsvp111 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP111() {
        return cpsvp111;
    }

    /**
     * Sets the value of the cpsvp111 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP111(String value) {
        this.cpsvp111 = value;
    }

    /**
     * Gets the value of the cpsvp112 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP112() {
        return cpsvp112;
    }

    /**
     * Sets the value of the cpsvp112 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP112(String value) {
        this.cpsvp112 = value;
    }

    /**
     * Gets the value of the cpsvp114 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP114() {
        return cpsvp114;
    }

    /**
     * Sets the value of the cpsvp114 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP114(String value) {
        this.cpsvp114 = value;
    }

    /**
     * Gets the value of the cpsvp115 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP115() {
        return cpsvp115;
    }

    /**
     * Sets the value of the cpsvp115 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP115(String value) {
        this.cpsvp115 = value;
    }

    /**
     * Gets the value of the cpsvp116 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP116() {
        return cpsvp116;
    }

    /**
     * Sets the value of the cpsvp116 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP116(String value) {
        this.cpsvp116 = value;
    }

    /**
     * Gets the value of the cpsvp117 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP117() {
        return cpsvp117;
    }

    /**
     * Sets the value of the cpsvp117 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP117(String value) {
        this.cpsvp117 = value;
    }

    /**
     * Gets the value of the cpsvp118 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP118() {
        return cpsvp118;
    }

    /**
     * Sets the value of the cpsvp118 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP118(String value) {
        this.cpsvp118 = value;
    }

    /**
     * Gets the value of the cpsvp119 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP119() {
        return cpsvp119;
    }

    /**
     * Sets the value of the cpsvp119 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP119(String value) {
        this.cpsvp119 = value;
    }

    /**
     * Gets the value of the cpsvp120 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP120() {
        return cpsvp120;
    }

    /**
     * Sets the value of the cpsvp120 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP120(String value) {
        this.cpsvp120 = value;
    }

    /**
     * Gets the value of the cpsvp121 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP121() {
        return cpsvp121;
    }

    /**
     * Sets the value of the cpsvp121 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP121(String value) {
        this.cpsvp121 = value;
    }

    /**
     * Gets the value of the cpsvp122 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP122() {
        return cpsvp122;
    }

    /**
     * Sets the value of the cpsvp122 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP122(String value) {
        this.cpsvp122 = value;
    }

    /**
     * Gets the value of the cpsvp123 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP123() {
        return cpsvp123;
    }

    /**
     * Sets the value of the cpsvp123 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP123(String value) {
        this.cpsvp123 = value;
    }

    /**
     * Gets the value of the cpsvp124 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP124() {
        return cpsvp124;
    }

    /**
     * Sets the value of the cpsvp124 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP124(String value) {
        this.cpsvp124 = value;
    }

    /**
     * Gets the value of the cpsvp125 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP125() {
        return cpsvp125;
    }

    /**
     * Sets the value of the cpsvp125 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP125(String value) {
        this.cpsvp125 = value;
    }

    /**
     * Gets the value of the cpsvp126 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP126() {
        return cpsvp126;
    }

    /**
     * Sets the value of the cpsvp126 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP126(String value) {
        this.cpsvp126 = value;
    }

    /**
     * Gets the value of the cpsvp127 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP127() {
        return cpsvp127;
    }

    /**
     * Sets the value of the cpsvp127 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP127(String value) {
        this.cpsvp127 = value;
    }

    /**
     * Gets the value of the cpsvp128 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP128() {
        return cpsvp128;
    }

    /**
     * Sets the value of the cpsvp128 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP128(String value) {
        this.cpsvp128 = value;
    }

    /**
     * Gets the value of the cpsvp130 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP130() {
        return cpsvp130;
    }

    /**
     * Sets the value of the cpsvp130 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP130(String value) {
        this.cpsvp130 = value;
    }

    /**
     * Gets the value of the cpsvp131 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP131() {
        return cpsvp131;
    }

    /**
     * Sets the value of the cpsvp131 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP131(String value) {
        this.cpsvp131 = value;
    }

    /**
     * Gets the value of the cpsvp132 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP132() {
        return cpsvp132;
    }

    /**
     * Sets the value of the cpsvp132 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP132(String value) {
        this.cpsvp132 = value;
    }

    /**
     * Gets the value of the cpsvp133 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP133() {
        return cpsvp133;
    }

    /**
     * Sets the value of the cpsvp133 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP133(String value) {
        this.cpsvp133 = value;
    }

    /**
     * Gets the value of the cpsvp134 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP134() {
        return cpsvp134;
    }

    /**
     * Sets the value of the cpsvp134 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP134(String value) {
        this.cpsvp134 = value;
    }

    /**
     * Gets the value of the cpsvp135 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP135() {
        return cpsvp135;
    }

    /**
     * Sets the value of the cpsvp135 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP135(String value) {
        this.cpsvp135 = value;
    }

    /**
     * Gets the value of the cpsvp136 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP136() {
        return cpsvp136;
    }

    /**
     * Sets the value of the cpsvp136 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP136(String value) {
        this.cpsvp136 = value;
    }

    /**
     * Gets the value of the cpsvp137 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP137() {
        return cpsvp137;
    }

    /**
     * Sets the value of the cpsvp137 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP137(String value) {
        this.cpsvp137 = value;
    }

    /**
     * Gets the value of the cpsvp138 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP138() {
        return cpsvp138;
    }

    /**
     * Sets the value of the cpsvp138 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP138(String value) {
        this.cpsvp138 = value;
    }

    /**
     * Gets the value of the cpsvp139 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP139() {
        return cpsvp139;
    }

    /**
     * Sets the value of the cpsvp139 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP139(String value) {
        this.cpsvp139 = value;
    }

    /**
     * Gets the value of the cpsvp140 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP140() {
        return cpsvp140;
    }

    /**
     * Sets the value of the cpsvp140 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP140(String value) {
        this.cpsvp140 = value;
    }

    /**
     * Gets the value of the cpsvp141 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP141() {
        return cpsvp141;
    }

    /**
     * Sets the value of the cpsvp141 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP141(String value) {
        this.cpsvp141 = value;
    }

    /**
     * Gets the value of the cpsvp142 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP142() {
        return cpsvp142;
    }

    /**
     * Sets the value of the cpsvp142 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP142(String value) {
        this.cpsvp142 = value;
    }

    /**
     * Gets the value of the cpsvp143 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP143() {
        return cpsvp143;
    }

    /**
     * Sets the value of the cpsvp143 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP143(String value) {
        this.cpsvp143 = value;
    }

    /**
     * Gets the value of the cpsvp144 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP144() {
        return cpsvp144;
    }

    /**
     * Sets the value of the cpsvp144 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP144(String value) {
        this.cpsvp144 = value;
    }

    /**
     * Gets the value of the cpsvp145 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP145() {
        return cpsvp145;
    }

    /**
     * Sets the value of the cpsvp145 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP145(String value) {
        this.cpsvp145 = value;
    }

    /**
     * Gets the value of the cpsvp147 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP147() {
        return cpsvp147;
    }

    /**
     * Sets the value of the cpsvp147 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP147(String value) {
        this.cpsvp147 = value;
    }

    /**
     * Gets the value of the cpsvp148 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP148() {
        return cpsvp148;
    }

    /**
     * Sets the value of the cpsvp148 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP148(String value) {
        this.cpsvp148 = value;
    }

    /**
     * Gets the value of the cpsvp149 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP149() {
        return cpsvp149;
    }

    /**
     * Sets the value of the cpsvp149 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP149(String value) {
        this.cpsvp149 = value;
    }

    /**
     * Gets the value of the cpsvp150 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP150() {
        return cpsvp150;
    }

    /**
     * Sets the value of the cpsvp150 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP150(String value) {
        this.cpsvp150 = value;
    }

    /**
     * Gets the value of the cpsvp151 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP151() {
        return cpsvp151;
    }

    /**
     * Sets the value of the cpsvp151 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP151(String value) {
        this.cpsvp151 = value;
    }

    /**
     * Gets the value of the cpsvp152 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP152() {
        return cpsvp152;
    }

    /**
     * Sets the value of the cpsvp152 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP152(String value) {
        this.cpsvp152 = value;
    }

    /**
     * Gets the value of the cpsvp153 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP153() {
        return cpsvp153;
    }

    /**
     * Sets the value of the cpsvp153 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP153(String value) {
        this.cpsvp153 = value;
    }

    /**
     * Gets the value of the cpsvp154 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP154() {
        return cpsvp154;
    }

    /**
     * Sets the value of the cpsvp154 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP154(String value) {
        this.cpsvp154 = value;
    }

    /**
     * Gets the value of the cpsvp155 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP155() {
        return cpsvp155;
    }

    /**
     * Sets the value of the cpsvp155 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP155(String value) {
        this.cpsvp155 = value;
    }

    /**
     * Gets the value of the cpsvp156 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP156() {
        return cpsvp156;
    }

    /**
     * Sets the value of the cpsvp156 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP156(String value) {
        this.cpsvp156 = value;
    }

    /**
     * Gets the value of the cpsvp157 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP157() {
        return cpsvp157;
    }

    /**
     * Sets the value of the cpsvp157 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP157(String value) {
        this.cpsvp157 = value;
    }

    /**
     * Gets the value of the cpsvp158 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP158() {
        return cpsvp158;
    }

    /**
     * Sets the value of the cpsvp158 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP158(String value) {
        this.cpsvp158 = value;
    }

    /**
     * Gets the value of the cpsvp159 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP159() {
        return cpsvp159;
    }

    /**
     * Sets the value of the cpsvp159 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP159(String value) {
        this.cpsvp159 = value;
    }

    /**
     * Gets the value of the cpsvp160 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP160() {
        return cpsvp160;
    }

    /**
     * Sets the value of the cpsvp160 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP160(String value) {
        this.cpsvp160 = value;
    }

    /**
     * Gets the value of the cpsvp161 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP161() {
        return cpsvp161;
    }

    /**
     * Sets the value of the cpsvp161 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP161(String value) {
        this.cpsvp161 = value;
    }

    /**
     * Gets the value of the cpsvp163 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP163() {
        return cpsvp163;
    }

    /**
     * Sets the value of the cpsvp163 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP163(String value) {
        this.cpsvp163 = value;
    }

    /**
     * Gets the value of the cpsvp164 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP164() {
        return cpsvp164;
    }

    /**
     * Sets the value of the cpsvp164 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP164(String value) {
        this.cpsvp164 = value;
    }

    /**
     * Gets the value of the cpsvp165 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP165() {
        return cpsvp165;
    }

    /**
     * Sets the value of the cpsvp165 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP165(String value) {
        this.cpsvp165 = value;
    }

    /**
     * Gets the value of the cpsvp166 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP166() {
        return cpsvp166;
    }

    /**
     * Sets the value of the cpsvp166 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP166(String value) {
        this.cpsvp166 = value;
    }

    /**
     * Gets the value of the cpsvp167 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP167() {
        return cpsvp167;
    }

    /**
     * Sets the value of the cpsvp167 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP167(String value) {
        this.cpsvp167 = value;
    }

    /**
     * Gets the value of the cpsvp168 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP168() {
        return cpsvp168;
    }

    /**
     * Sets the value of the cpsvp168 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP168(String value) {
        this.cpsvp168 = value;
    }

    /**
     * Gets the value of the cpsvp169 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP169() {
        return cpsvp169;
    }

    /**
     * Sets the value of the cpsvp169 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP169(String value) {
        this.cpsvp169 = value;
    }

    /**
     * Gets the value of the cpsvp170 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP170() {
        return cpsvp170;
    }

    /**
     * Sets the value of the cpsvp170 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP170(String value) {
        this.cpsvp170 = value;
    }

    /**
     * Gets the value of the cpsvp171 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP171() {
        return cpsvp171;
    }

    /**
     * Sets the value of the cpsvp171 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP171(String value) {
        this.cpsvp171 = value;
    }

    /**
     * Gets the value of the cpsvp172 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP172() {
        return cpsvp172;
    }

    /**
     * Sets the value of the cpsvp172 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP172(String value) {
        this.cpsvp172 = value;
    }

    /**
     * Gets the value of the cpsvp173 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP173() {
        return cpsvp173;
    }

    /**
     * Sets the value of the cpsvp173 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP173(String value) {
        this.cpsvp173 = value;
    }

    /**
     * Gets the value of the cpsvp174 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP174() {
        return cpsvp174;
    }

    /**
     * Sets the value of the cpsvp174 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP174(String value) {
        this.cpsvp174 = value;
    }

    /**
     * Gets the value of the cpsvp175 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP175() {
        return cpsvp175;
    }

    /**
     * Sets the value of the cpsvp175 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP175(String value) {
        this.cpsvp175 = value;
    }

    /**
     * Gets the value of the cpsvp176 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP176() {
        return cpsvp176;
    }

    /**
     * Sets the value of the cpsvp176 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP176(String value) {
        this.cpsvp176 = value;
    }

    /**
     * Gets the value of the cpsvp177 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP177() {
        return cpsvp177;
    }

    /**
     * Sets the value of the cpsvp177 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP177(String value) {
        this.cpsvp177 = value;
    }

    /**
     * Gets the value of the cpsvp179 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP179() {
        return cpsvp179;
    }

    /**
     * Sets the value of the cpsvp179 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP179(String value) {
        this.cpsvp179 = value;
    }

    /**
     * Gets the value of the cpsvp180 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP180() {
        return cpsvp180;
    }

    /**
     * Sets the value of the cpsvp180 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP180(String value) {
        this.cpsvp180 = value;
    }

    /**
     * Gets the value of the cpsvp181 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP181() {
        return cpsvp181;
    }

    /**
     * Sets the value of the cpsvp181 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP181(String value) {
        this.cpsvp181 = value;
    }

    /**
     * Gets the value of the cpsvp182 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP182() {
        return cpsvp182;
    }

    /**
     * Sets the value of the cpsvp182 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP182(String value) {
        this.cpsvp182 = value;
    }

    /**
     * Gets the value of the cpsvp183 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP183() {
        return cpsvp183;
    }

    /**
     * Sets the value of the cpsvp183 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP183(String value) {
        this.cpsvp183 = value;
    }

    /**
     * Gets the value of the cpsvp184 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP184() {
        return cpsvp184;
    }

    /**
     * Sets the value of the cpsvp184 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP184(String value) {
        this.cpsvp184 = value;
    }

    /**
     * Gets the value of the cpsvp185 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP185() {
        return cpsvp185;
    }

    /**
     * Sets the value of the cpsvp185 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP185(String value) {
        this.cpsvp185 = value;
    }

    /**
     * Gets the value of the cpsvp186 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP186() {
        return cpsvp186;
    }

    /**
     * Sets the value of the cpsvp186 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP186(String value) {
        this.cpsvp186 = value;
    }

    /**
     * Gets the value of the cpsvp187 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP187() {
        return cpsvp187;
    }

    /**
     * Sets the value of the cpsvp187 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP187(String value) {
        this.cpsvp187 = value;
    }

    /**
     * Gets the value of the cpsvp188 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP188() {
        return cpsvp188;
    }

    /**
     * Sets the value of the cpsvp188 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP188(String value) {
        this.cpsvp188 = value;
    }

    /**
     * Gets the value of the cpsvp189 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP189() {
        return cpsvp189;
    }

    /**
     * Sets the value of the cpsvp189 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP189(String value) {
        this.cpsvp189 = value;
    }

    /**
     * Gets the value of the cpsvp190 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP190() {
        return cpsvp190;
    }

    /**
     * Sets the value of the cpsvp190 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP190(String value) {
        this.cpsvp190 = value;
    }

    /**
     * Gets the value of the cpsvp191 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP191() {
        return cpsvp191;
    }

    /**
     * Sets the value of the cpsvp191 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP191(String value) {
        this.cpsvp191 = value;
    }

    /**
     * Gets the value of the cpsvp192 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP192() {
        return cpsvp192;
    }

    /**
     * Sets the value of the cpsvp192 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP192(String value) {
        this.cpsvp192 = value;
    }

    /**
     * Gets the value of the cpsvp193 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVP193() {
        return cpsvp193;
    }

    /**
     * Sets the value of the cpsvp193 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVP193(String value) {
        this.cpsvp193 = value;
    }

    /**
     * Gets the value of the cpsvs646 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS646() {
        return cpsvs646;
    }

    /**
     * Sets the value of the cpsvs646 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS646(String value) {
        this.cpsvs646 = value;
    }

    /**
     * Gets the value of the cpsvs647 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS647() {
        return cpsvs647;
    }

    /**
     * Sets the value of the cpsvs647 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS647(String value) {
        this.cpsvs647 = value;
    }

    /**
     * Gets the value of the cpsvs648 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS648() {
        return cpsvs648;
    }

    /**
     * Sets the value of the cpsvs648 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS648(String value) {
        this.cpsvs648 = value;
    }

    /**
     * Gets the value of the cpsvs649 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS649() {
        return cpsvs649;
    }

    /**
     * Sets the value of the cpsvs649 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS649(String value) {
        this.cpsvs649 = value;
    }

    /**
     * Gets the value of the cpsvs650 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS650() {
        return cpsvs650;
    }

    /**
     * Sets the value of the cpsvs650 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS650(String value) {
        this.cpsvs650 = value;
    }

    /**
     * Gets the value of the cpsvs651 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS651() {
        return cpsvs651;
    }

    /**
     * Sets the value of the cpsvs651 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS651(String value) {
        this.cpsvs651 = value;
    }

    /**
     * Gets the value of the cpsvs652 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS652() {
        return cpsvs652;
    }

    /**
     * Sets the value of the cpsvs652 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS652(String value) {
        this.cpsvs652 = value;
    }

    /**
     * Gets the value of the cpsvs653 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS653() {
        return cpsvs653;
    }

    /**
     * Sets the value of the cpsvs653 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS653(String value) {
        this.cpsvs653 = value;
    }

    /**
     * Gets the value of the cpsvs654 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS654() {
        return cpsvs654;
    }

    /**
     * Sets the value of the cpsvs654 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS654(String value) {
        this.cpsvs654 = value;
    }

    /**
     * Gets the value of the cpsvs655 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS655() {
        return cpsvs655;
    }

    /**
     * Sets the value of the cpsvs655 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS655(String value) {
        this.cpsvs655 = value;
    }

    /**
     * Gets the value of the cpsvs656 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS656() {
        return cpsvs656;
    }

    /**
     * Sets the value of the cpsvs656 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS656(String value) {
        this.cpsvs656 = value;
    }

    /**
     * Gets the value of the cpsvs657 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS657() {
        return cpsvs657;
    }

    /**
     * Sets the value of the cpsvs657 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS657(String value) {
        this.cpsvs657 = value;
    }

    /**
     * Gets the value of the cpsvs658 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS658() {
        return cpsvs658;
    }

    /**
     * Sets the value of the cpsvs658 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS658(String value) {
        this.cpsvs658 = value;
    }

    /**
     * Gets the value of the cpsvs659 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS659() {
        return cpsvs659;
    }

    /**
     * Sets the value of the cpsvs659 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS659(String value) {
        this.cpsvs659 = value;
    }

    /**
     * Gets the value of the cpsvs660 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS660() {
        return cpsvs660;
    }

    /**
     * Sets the value of the cpsvs660 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS660(String value) {
        this.cpsvs660 = value;
    }

    /**
     * Gets the value of the cpsvs661 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS661() {
        return cpsvs661;
    }

    /**
     * Sets the value of the cpsvs661 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS661(String value) {
        this.cpsvs661 = value;
    }

    /**
     * Gets the value of the cpsvs662 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS662() {
        return cpsvs662;
    }

    /**
     * Sets the value of the cpsvs662 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS662(String value) {
        this.cpsvs662 = value;
    }

    /**
     * Gets the value of the cpsvs663 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS663() {
        return cpsvs663;
    }

    /**
     * Sets the value of the cpsvs663 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS663(String value) {
        this.cpsvs663 = value;
    }

    /**
     * Gets the value of the cpsvs664 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS664() {
        return cpsvs664;
    }

    /**
     * Sets the value of the cpsvs664 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS664(String value) {
        this.cpsvs664 = value;
    }

    /**
     * Gets the value of the cpsvs665 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS665() {
        return cpsvs665;
    }

    /**
     * Sets the value of the cpsvs665 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS665(String value) {
        this.cpsvs665 = value;
    }

    /**
     * Gets the value of the cpsvs666 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS666() {
        return cpsvs666;
    }

    /**
     * Sets the value of the cpsvs666 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS666(String value) {
        this.cpsvs666 = value;
    }

    /**
     * Gets the value of the cpsvs667 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS667() {
        return cpsvs667;
    }

    /**
     * Sets the value of the cpsvs667 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS667(String value) {
        this.cpsvs667 = value;
    }

    /**
     * Gets the value of the cpsvs668 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS668() {
        return cpsvs668;
    }

    /**
     * Sets the value of the cpsvs668 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS668(String value) {
        this.cpsvs668 = value;
    }

    /**
     * Gets the value of the cpsvs669 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS669() {
        return cpsvs669;
    }

    /**
     * Sets the value of the cpsvs669 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS669(String value) {
        this.cpsvs669 = value;
    }

    /**
     * Gets the value of the cpsvs670 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS670() {
        return cpsvs670;
    }

    /**
     * Sets the value of the cpsvs670 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS670(String value) {
        this.cpsvs670 = value;
    }

    /**
     * Gets the value of the cpsvs671 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS671() {
        return cpsvs671;
    }

    /**
     * Sets the value of the cpsvs671 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS671(String value) {
        this.cpsvs671 = value;
    }

    /**
     * Gets the value of the cpsvs672 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS672() {
        return cpsvs672;
    }

    /**
     * Sets the value of the cpsvs672 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS672(String value) {
        this.cpsvs672 = value;
    }

    /**
     * Gets the value of the cpsvs673 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS673() {
        return cpsvs673;
    }

    /**
     * Sets the value of the cpsvs673 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS673(String value) {
        this.cpsvs673 = value;
    }

    /**
     * Gets the value of the cpsvs674 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS674() {
        return cpsvs674;
    }

    /**
     * Sets the value of the cpsvs674 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS674(String value) {
        this.cpsvs674 = value;
    }

    /**
     * Gets the value of the cpsvs675 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVS675() {
        return cpsvs675;
    }

    /**
     * Sets the value of the cpsvs675 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVS675(String value) {
        this.cpsvs675 = value;
    }

    /**
     * Gets the value of the idrssd property.
     * 
     */
    public int getIDRSSD() {
        return idrssd;
    }

    /**
     * Sets the value of the idrssd property.
     * 
     */
    public void setIDRSSD(int value) {
        this.idrssd = value;
    }

    /**
     * Gets the value of the ddt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDDT() {
        return ddt;
    }

    /**
     * Sets the value of the ddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDDT(XMLGregorianCalendar value) {
        this.ddt = value;
    }

    /**
     * Gets the value of the ccarp006 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCARP006() {
        return ccarp006;
    }

    /**
     * Sets the value of the ccarp006 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCARP006(String value) {
        this.ccarp006 = value;
    }

    /**
     * Gets the value of the cpsvn998 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSVN998() {
        return cpsvn998;
    }

    /**
     * Sets the value of the cpsvn998 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSVN998(String value) {
        this.cpsvn998 = value;
    }

    /**
     * Gets the value of the transtype property.
     * 
     * @return
     *     possible object is
     *     {@link TRANSTYPEIUD }
     *     
     */
    public TRANSTYPEIUD getTRANSTYPE() {
        return transtype;
    }

    /**
     * Sets the value of the transtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRANSTYPEIUD }
     *     
     */
    public void setTRANSTYPE(TRANSTYPEIUD value) {
        this.transtype = value;
    }

}
