//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.15 at 01:11:28 PM CST 
//


package com.bny.castxc.schedule.summary;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="CPSPN234" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSPN235" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSPB530" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSPP088" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSPS677" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSPS678" type="{}STRING_50" minOccurs="0"/>
 *         &lt;element name="CPSMN244" type="{}STRING_50" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="ID_RSSD" use="required" type="{}INTEGER" />
 *       &lt;attribute name="D_DT" use="required" type="{}DATE_TIME" />
 *       &lt;attribute name="CCARP006" use="required" type="{}STRING_50" />
 *       &lt;attribute name="CCARP009" use="required" type="{}STRING_25" />
 *       &lt;attribute name="CCARP092" use="required" type="{}STRING_50" />
 *       &lt;attribute name="CCARP084" use="required" type="{}STRING_100" />
 *       &lt;attribute name="TRANSTYPE" use="required" type="{}TRANSTYPE_IUD" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "SMRY_Data_Collect_OTTI_PROJ")
public class SMRYDataCollectOTTIPROJ {

    @XmlElement(name = "CPSPN234")
    protected String cpspn234;
    @XmlElement(name = "CPSPN235")
    protected String cpspn235;
    @XmlElement(name = "CPSPB530")
    protected String cpspb530;
    @XmlElement(name = "CPSPP088")
    protected String cpspp088;
    @XmlElement(name = "CPSPS677")
    protected String cpsps677;
    @XmlElement(name = "CPSPS678")
    protected String cpsps678;
    @XmlElement(name = "CPSMN244")
    protected String cpsmn244;
    @XmlAttribute(name = "ID_RSSD", required = true)
    protected int idrssd;
    @XmlAttribute(name = "D_DT", required = true)
    protected XMLGregorianCalendar ddt;
    @XmlAttribute(name = "CCARP006", required = true)
    protected String ccarp006;
    @XmlAttribute(name = "CCARP009", required = true)
    protected String ccarp009;
    @XmlAttribute(name = "CCARP092", required = true)
    protected String ccarp092;
    @XmlAttribute(name = "CCARP084", required = true)
    protected String ccarp084;
    @XmlAttribute(name = "TRANSTYPE", required = true)
    protected TRANSTYPEIUD transtype;

    /**
     * Gets the value of the cpspn234 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSPN234() {
        return cpspn234;
    }

    /**
     * Sets the value of the cpspn234 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSPN234(String value) {
        this.cpspn234 = value;
    }

    /**
     * Gets the value of the cpspn235 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSPN235() {
        return cpspn235;
    }

    /**
     * Sets the value of the cpspn235 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSPN235(String value) {
        this.cpspn235 = value;
    }

    /**
     * Gets the value of the cpspb530 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSPB530() {
        return cpspb530;
    }

    /**
     * Sets the value of the cpspb530 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSPB530(String value) {
        this.cpspb530 = value;
    }

    /**
     * Gets the value of the cpspp088 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSPP088() {
        return cpspp088;
    }

    /**
     * Sets the value of the cpspp088 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSPP088(String value) {
        this.cpspp088 = value;
    }

    /**
     * Gets the value of the cpsps677 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSPS677() {
        return cpsps677;
    }

    /**
     * Sets the value of the cpsps677 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSPS677(String value) {
        this.cpsps677 = value;
    }

    /**
     * Gets the value of the cpsps678 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSPS678() {
        return cpsps678;
    }

    /**
     * Sets the value of the cpsps678 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSPS678(String value) {
        this.cpsps678 = value;
    }

    /**
     * Gets the value of the cpsmn244 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCPSMN244() {
        return cpsmn244;
    }

    /**
     * Sets the value of the cpsmn244 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCPSMN244(String value) {
        this.cpsmn244 = value;
    }

    /**
     * Gets the value of the idrssd property.
     * 
     */
    public int getIDRSSD() {
        return idrssd;
    }

    /**
     * Sets the value of the idrssd property.
     * 
     */
    public void setIDRSSD(int value) {
        this.idrssd = value;
    }

    /**
     * Gets the value of the ddt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDDT() {
        return ddt;
    }

    /**
     * Sets the value of the ddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDDT(XMLGregorianCalendar value) {
        this.ddt = value;
    }

    /**
     * Gets the value of the ccarp006 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCARP006() {
        return ccarp006;
    }

    /**
     * Sets the value of the ccarp006 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCARP006(String value) {
        this.ccarp006 = value;
    }

    /**
     * Gets the value of the ccarp009 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCARP009() {
        return ccarp009;
    }

    /**
     * Sets the value of the ccarp009 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCARP009(String value) {
        this.ccarp009 = value;
    }

    /**
     * Gets the value of the ccarp092 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCARP092() {
        return ccarp092;
    }

    /**
     * Sets the value of the ccarp092 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCARP092(String value) {
        this.ccarp092 = value;
    }

    /**
     * Gets the value of the ccarp084 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCARP084() {
        return ccarp084;
    }

    /**
     * Sets the value of the ccarp084 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCARP084(String value) {
        this.ccarp084 = value;
    }

    /**
     * Gets the value of the transtype property.
     * 
     * @return
     *     possible object is
     *     {@link TRANSTYPEIUD }
     *     
     */
    public TRANSTYPEIUD getTRANSTYPE() {
        return transtype;
    }

    /**
     * Sets the value of the transtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRANSTYPEIUD }
     *     
     */
    public void setTRANSTYPE(TRANSTYPEIUD value) {
        this.transtype = value;
    }

}
